import os
import shutil
import PyInstaller.__main__
import subprocess
import sys
from datetime import datetime

def get_version():
    """获取并递增版本号"""
    version_file = 'build_version_info.py'
    default_version = '1.0.0'
    
    # 读取当前版本号
    current_version = default_version
    if os.path.exists(version_file):
        try:
            with open(version_file, 'r', encoding='utf-8') as f:
                content = f.read()
                # 从文件中提取VERSION值
                import re
                match = re.search(r'VERSION = "([^"]+)"', content)
                if match:
                    current_version = match.group(1)
        except:
            current_version = default_version
    
    # 解析版本号
    try:
        parts = current_version.split('.')
        major, minor, patch = int(parts[0]), int(parts[1]), int(parts[2])
    except:
        major, minor, patch = 1, 0, 0
    
    # 递增修订号
    patch += 1
    new_version = f"{major}.{minor}.{patch}"
    
    print(f"✅ 版本号: {current_version} -> {new_version}")
    return new_version

def get_git_info():
    """获取Git信息"""
    git_info = {
        'commit_hash': 'Unknown',
        'commit_message': 'Unknown',
        'commit_author': 'Unknown',
        'commit_date': 'Unknown',
        'branch': 'Unknown'
    }
    
    try:
        # 获取当前分支
        result = subprocess.run(['git', 'rev-parse', '--abbrev-ref', 'HEAD'], 
                              capture_output=True, text=True, encoding='utf-8', 
                              errors='ignore', check=True)
        git_info['branch'] = result.stdout.strip()
        
        # 获取最新commit hash（短）
        result = subprocess.run(['git', 'rev-parse', '--short', 'HEAD'], 
                              capture_output=True, text=True, encoding='utf-8',
                              errors='ignore', check=True)
        git_info['commit_hash'] = result.stdout.strip()
        
        # 获取最新commit信息
        result = subprocess.run(['git', 'log', '-1', '--pretty=format:%s'], 
                              capture_output=True, text=True, encoding='utf-8',
                              errors='ignore', check=True)
        git_info['commit_message'] = result.stdout.strip() if result.stdout else 'Unknown'
        
        # 获取最新commit作者
        result = subprocess.run(['git', 'log', '-1', '--pretty=format:%an'], 
                              capture_output=True, text=True, encoding='utf-8',
                              errors='ignore', check=True)
        git_info['commit_author'] = result.stdout.strip() if result.stdout else 'Unknown'
        
        # 获取最新commit日期
        result = subprocess.run(['git', 'log', '-1', '--pretty=format:%ci'], 
                              capture_output=True, text=True, encoding='utf-8',
                              errors='ignore', check=True)
        git_info['commit_date'] = result.stdout.strip() if result.stdout else 'Unknown'
        
        print(f"✅ Git信息获取成功:")
        print(f"   分支: {git_info['branch']}")
        print(f"   Commit: {git_info['commit_hash']} - {git_info['commit_message']}")
        print(f"   作者: {git_info['commit_author']}")
        print(f"   提交时间: {git_info['commit_date']}")
        
    except subprocess.CalledProcessError as e:
        print(f"⚠️  无法获取Git信息（可能不在Git仓库中）: {e}")
    except FileNotFoundError:
        print("⚠️  Git命令未找到")
    except Exception as e:
        print(f"⚠️  获取Git信息时出错: {e}")
    
    return git_info

def generate_version_info(build_date, git_info, version):
    """生成版本信息文件"""
    version_content = f'''# Auto-generated by build_enhance.py
# DO NOT EDIT MANUALLY

VERSION = "{version}"
BUILD_DATE = "{build_date}"
GIT_BRANCH = "{git_info['branch']}"
GIT_COMMIT_HASH = "{git_info['commit_hash']}"
GIT_COMMIT_MESSAGE = "{git_info['commit_message']}"
GIT_COMMIT_AUTHOR = "{git_info['commit_author']}"
GIT_COMMIT_DATE = "{git_info['commit_date']}"

def get_version_string():
    """获取完整的版本信息字符串"""
    return f"v{{VERSION}} | 打包: {{BUILD_DATE}} | Commit: {{GIT_COMMIT_HASH}} ({{GIT_BRANCH}}) | {{GIT_COMMIT_AUTHOR}} | {{GIT_COMMIT_MESSAGE}}"

def get_detailed_info():
    """获取详细信息"""
    return {{
        'version': VERSION,
        'build_date': BUILD_DATE,
        'git_branch': GIT_BRANCH,
        'git_commit_hash': GIT_COMMIT_HASH,
        'git_commit_message': GIT_COMMIT_MESSAGE,
        'git_commit_author': GIT_COMMIT_AUTHOR,
        'git_commit_date': GIT_COMMIT_DATE
    }}
'''
    
    with open('build_version_info.py', 'w', encoding='utf-8') as f:
        f.write(version_content)
    
    print(f"✅ 版本信息文件已生成: build_version_info.py")

def build_exe(mode: str, version: str):
    """编译指定版本的EXE"""
    # 模式名称映射
    mode_names = {
        'factoryApp': '工厂版',
        'developerApp': '开发者版本',
        'firstuse': '首次使用版'
    }
    mode_name = mode_names.get(mode, mode)
    
    # firstuse保持简单命名，其他版本使用：【模式】安培上位机v版本号
    if mode == 'firstuse':
        exe_name = "firstuse"
        output_dir = "dist/firstuse"
    else:
        exe_name = f"【{mode_name}】安培上位机v{version}"
        output_dir = f"dist/{mode_name}_v{version}"
    
    print(f"正在编译 {mode_name} 版本...")
    print(f"文件名: {exe_name}.exe")
    
    # 清理旧构建文件
    shutil.rmtree("build", ignore_errors=True)
    shutil.rmtree(output_dir, ignore_errors=True)
    
    # 生成运行时钩子文件
    with open(f"runtime_hook_enhanced_{mode}.py", "w", encoding='utf-8') as f:
        f.write(f"import os\nos.environ['APP_MODE'] = '{mode}'")
    
    # 构建参数
    args = [
        "enhanced_main_window.py",
        f"--name={exe_name}",
        "--onefile",
        "--windowed",
        # f"--icon=build/icon.ico",
        "--add-data=测试上位机.ui;.",
        "--add-data=monitor_interface.ui;.",
        "--add-data=build_version_info.py;.",
        f"--distpath={output_dir}",
        # "--workpath=build",
        # "--specpath=build",
        f"--runtime-hook=runtime_hook_enhanced_{mode}.py",
        "--clean",
        "--noconfirm",
        # 排除PySide6以避免冲突
        "--exclude-module=PySide6",
        "--exclude-module=PySide6.QtCore",
        "--exclude-module=PySide6.QtGui", 
        "--exclude-module=PySide6.QtWidgets",
        "--exclude-module=shiboken6"
    ]
    
    # 调试版额外配置
    if mode in ["developerApp"]:
        args += [
            "--debug=all",
            "--console"  # 调试版显示控制台
        ]
    
    PyInstaller.__main__.run(args)
    os.remove(f"runtime_hook_enhanced_{mode}.py")  # 清理临时文件
    
    return output_dir, exe_name

def convert_ui_to_py(ui_file, py_file):
    """转换UI文件为Python文件 - 使用PyQt6"""
    try:
        # 使用PyQt6的pyuic6工具
        result = subprocess.run([
            'pyuic6', ui_file, '-o', py_file
        ], check=True, capture_output=True, text=True)
        
        print(f"UI转换成功: {ui_file} -> {py_file}")
        return True
    except subprocess.CalledProcessError as e:
        print(f"UI转换失败: {e}")
        print(f"错误输出: {e.stderr}")
        return False
    except FileNotFoundError:
        print("pyuic6 命令未找到，尝试使用 Python 模块方式...")
        try:
            # 使用 Python -m PyQt6.uic.pyuic 方式调用
            result = subprocess.run([
                sys.executable, '-m', 'PyQt6.uic.pyuic',
                ui_file, '-o', py_file
            ], check=True, capture_output=True, text=True)
            
            print(f"UI转换成功: {ui_file} -> {py_file}")
            return True
        except subprocess.CalledProcessError as e:
            print(f"Python模块方式也失败: {e}")
            return False

if __name__ == "__main__":
    print("=" * 60)
    print("增强版BMS调试工具打包脚本")
    print("=" * 60)
    
    # 步骤1: 获取并递增版本号
    print("\n步骤1: 获取版本号...")
    version = get_version()
    
    # 步骤2: 获取Git信息
    print("\n步骤2: 获取Git信息...")
    build_date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    git_info = get_git_info()
    
    # 步骤3: 生成版本信息文件
    print("\n步骤3: 生成版本信息文件...")
    generate_version_info(build_date, git_info, version)
    
    # 步骤4: 转换UI文件
    print("\n步骤4: 转换UI文件...")
    
    # 步骤5: 编译版本
    print("\n步骤5: 编译可执行文件...")
    built_files = []
    for mode in ["factoryApp", "firstuse"]:
        print(f"\n{'='*50}")
        output_dir, exe_name = build_exe(mode, version)
        built_files.append((output_dir, exe_name))
    
    print("\n" + "=" * 60)
    print("编译完成！")
    print("=" * 60)
    print("\n📦 打包版本信息:")
    print(f"  版本号: v{version}")
    print(f"  打包时间: {build_date}")
    print(f"  Git分支: {git_info['branch']}")
    print(f"  Commit: {git_info['commit_hash']}")
    print(f"  提交信息: {git_info['commit_message']}")
    print(f"  提交作者: {git_info['commit_author']}")
    print(f"  提交时间: {git_info['commit_date']}")
    print("\n📂 生成的 EXE 位置：")
    for output_dir, exe_name in built_files:
        print(f"  - {output_dir}/{exe_name}.exe")
    print("=" * 60)

