import os
import shutil
import PyInstaller.__main__
import subprocess
import sys
from datetime import datetime

def get_git_info():
    """获取Git信息"""
    git_info = {
        'commit_hash': 'Unknown',
        'commit_message': 'Unknown',
        'commit_author': 'Unknown',
        'commit_date': 'Unknown',
        'branch': 'Unknown'
    }
    
    try:
        # 获取当前分支
        result = subprocess.run(['git', 'rev-parse', '--abbrev-ref', 'HEAD'], 
                              capture_output=True, text=True, encoding='utf-8', 
                              errors='ignore', check=True)
        git_info['branch'] = result.stdout.strip()
        
        # 获取最新commit hash（短）
        result = subprocess.run(['git', 'rev-parse', '--short', 'HEAD'], 
                              capture_output=True, text=True, encoding='utf-8',
                              errors='ignore', check=True)
        git_info['commit_hash'] = result.stdout.strip()
        
        # 获取最新commit信息
        result = subprocess.run(['git', 'log', '-1', '--pretty=format:%s'], 
                              capture_output=True, text=True, encoding='utf-8',
                              errors='ignore', check=True)
        git_info['commit_message'] = result.stdout.strip() if result.stdout else 'Unknown'
        
        # 获取最新commit作者
        result = subprocess.run(['git', 'log', '-1', '--pretty=format:%an'], 
                              capture_output=True, text=True, encoding='utf-8',
                              errors='ignore', check=True)
        git_info['commit_author'] = result.stdout.strip() if result.stdout else 'Unknown'
        
        # 获取最新commit日期
        result = subprocess.run(['git', 'log', '-1', '--pretty=format:%ci'], 
                              capture_output=True, text=True, encoding='utf-8',
                              errors='ignore', check=True)
        git_info['commit_date'] = result.stdout.strip() if result.stdout else 'Unknown'
        
        print(f"✅ Git信息获取成功:")
        print(f"   分支: {git_info['branch']}")
        print(f"   Commit: {git_info['commit_hash']} - {git_info['commit_message']}")
        print(f"   作者: {git_info['commit_author']}")
        print(f"   提交时间: {git_info['commit_date']}")
        
    except subprocess.CalledProcessError as e:
        print(f"⚠️  无法获取Git信息（可能不在Git仓库中）: {e}")
    except FileNotFoundError:
        print("⚠️  Git命令未找到")
    except Exception as e:
        print(f"⚠️  获取Git信息时出错: {e}")
    
    return git_info

def generate_version_info(build_date, git_info):
    """生成版本信息文件"""
    version_content = f'''# Auto-generated by build_enhance.py
# DO NOT EDIT MANUALLY

BUILD_DATE = "{build_date}"
GIT_BRANCH = "{git_info['branch']}"
GIT_COMMIT_HASH = "{git_info['commit_hash']}"
GIT_COMMIT_MESSAGE = "{git_info['commit_message']}"
GIT_COMMIT_AUTHOR = "{git_info['commit_author']}"
GIT_COMMIT_DATE = "{git_info['commit_date']}"

def get_version_string():
    """获取完整的版本信息字符串"""
    return f"打包: {{BUILD_DATE}} | Commit: {{GIT_COMMIT_HASH}} ({{GIT_BRANCH}}) | {{GIT_COMMIT_AUTHOR}} | {{GIT_COMMIT_MESSAGE}}"

def get_detailed_info():
    """获取详细信息"""
    return {{
        'build_date': BUILD_DATE,
        'git_branch': GIT_BRANCH,
        'git_commit_hash': GIT_COMMIT_HASH,
        'git_commit_message': GIT_COMMIT_MESSAGE,
        'git_commit_author': GIT_COMMIT_AUTHOR,
        'git_commit_date': GIT_COMMIT_DATE
    }}
'''
    
    with open('build_version_info.py', 'w', encoding='utf-8') as f:
        f.write(version_content)
    
    print(f"✅ 版本信息文件已生成: build_version_info.py")

def build_exe(mode: str):
    """编译指定版本的EXE"""
    print(f"正在编译增强版 {mode} 版本...")
    
    # 清理旧构建文件
    shutil.rmtree("build", ignore_errors=True)
    shutil.rmtree(f"dist/enhanced_{mode}_version", ignore_errors=True)
    
    # 生成运行时钩子文件
    with open(f"runtime_hook_enhanced_{mode}.py", "w") as f:
        f.write(f"import os\nos.environ['APP_MODE'] = '{mode}'")
    
    # 构建参数
    args = [
        "enhanced_main_window.py",
        f"--name=enhanced_{mode}",
        "--onefile",
        "--windowed",
        # f"--icon=build/icon.ico",
        "--add-data=测试上位机.ui;.",
        "--add-data=monitor_interface.ui;.",
        "--add-data=build_version_info.py;.",  # 打包版本信息文件
        f"--distpath=dist/enhanced_{mode}_version",
        # "--workpath=build",
        # "--specpath=build",
        f"--runtime-hook=runtime_hook_enhanced_{mode}.py",
        "--clean",
        "--noconfirm",
        # 排除PySide6以避免冲突
        "--exclude-module=PySide6",
        "--exclude-module=PySide6.QtCore",
        "--exclude-module=PySide6.QtGui", 
        "--exclude-module=PySide6.QtWidgets",
        "--exclude-module=shiboken6"
    ]
    
    # 调试版额外配置
    if mode in ["debugApp"]:
        args += [
            "--debug=all",
            "--console"  # 调试版显示控制台
        ]
    
    PyInstaller.__main__.run(args)
    os.remove(f"runtime_hook_enhanced_{mode}.py")  # 清理临时文件

def convert_ui_to_py(ui_file, py_file):
    """转换UI文件为Python文件 - 使用PyQt6"""
    try:
        # 使用PyQt6的pyuic6工具
        result = subprocess.run([
            'pyuic6', ui_file, '-o', py_file
        ], check=True, capture_output=True, text=True)
        
        print(f"UI转换成功: {ui_file} -> {py_file}")
        return True
    except subprocess.CalledProcessError as e:
        print(f"UI转换失败: {e}")
        print(f"错误输出: {e.stderr}")
        return False
    except FileNotFoundError:
        print("pyuic6 命令未找到，尝试使用 Python 模块方式...")
        try:
            # 使用 Python -m PyQt6.uic.pyuic 方式调用
            result = subprocess.run([
                sys.executable, '-m', 'PyQt6.uic.pyuic',
                ui_file, '-o', py_file
            ], check=True, capture_output=True, text=True)
            
            print(f"UI转换成功: {ui_file} -> {py_file}")
            return True
        except subprocess.CalledProcessError as e:
            print(f"Python模块方式也失败: {e}")
            return False

if __name__ == "__main__":
    print("=" * 60)
    print("增强版BMS调试工具打包脚本")
    print("=" * 60)
    
    # 步骤1: 获取版本信息
    print("\n步骤1: 获取版本信息...")
    build_date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    git_info = get_git_info()
    generate_version_info(build_date, git_info)
    
    # 步骤2: 转换UI文件
    print("\n步骤2: 转换UI文件...")
    
    # 步骤3: 编译版本
    print("\n步骤3: 编译可执行文件...")
    for mode in ["userApp", "debugApp", "firstuse"]:
        print(f"\n正在编译 {mode} 版本...")
        build_exe(mode)
    
    print("\n" + "=" * 60)
    print("编译完成！")
    print("=" * 60)
    print("\n📦 打包版本信息:")
    print(f"  打包时间: {build_date}")
    print(f"  Git分支: {git_info['branch']}")
    print(f"  Commit: {git_info['commit_hash']}")
    print(f"  提交信息: {git_info['commit_message']}")
    print(f"  提交作者: {git_info['commit_author']}")
    print(f"  提交时间: {git_info['commit_date']}")
    print("\n📂 生成的 EXE 位置：")
    print("  - 用户版: dist/enhanced_userApp_version/enhanced_userApp.exe")
    print("  - 调试版: dist/enhanced_debugApp_version/enhanced_debugApp.exe")
    print("  - 首次使用版: dist/enhanced_firstuse_version/enhanced_firstuse.exe")
    print("=" * 60)

