# Auto-generated by build_enhance.py
# DO NOT EDIT MANUALLY

VERSION = "3.0.14"
BUILD_DATE = "2026-04-15 16:02:02"
GIT_BRANCH = "print_ok"
GIT_COMMIT_HASH = "b0b1638"
GIT_COMMIT_MESSAGE = "pref: 烧录测试中，不再弹窗终止流程"
GIT_COMMIT_AUTHOR = "guoxuecheng"
GIT_COMMIT_DATE = "2026-04-15 16:01:50 +0800"

def get_version_string():
    """获取完整的版本信息字符串"""
    return f"v{VERSION} | 打包: {BUILD_DATE} | Commit: {GIT_COMMIT_HASH} ({GIT_BRANCH}) | {GIT_COMMIT_AUTHOR} | {GIT_COMMIT_MESSAGE}"

def get_detailed_info():
    """获取详细信息"""
    return {
        'version': VERSION,
        'build_date': BUILD_DATE,
        'git_branch': GIT_BRANCH,
        'git_commit_hash': GIT_COMMIT_HASH,
        'git_commit_message': GIT_COMMIT_MESSAGE,
        'git_commit_author': GIT_COMMIT_AUTHOR,
        'git_commit_date': GIT_COMMIT_DATE
    }
