# Auto-generated by build_enhance.py
# DO NOT EDIT MANUALLY

VERSION = "2.0.2"
BUILD_DATE = "2025-11-24 20:50:13"
GIT_BRANCH = "connect_wind_simplified"
GIT_COMMIT_HASH = "4b1d86c"
GIT_COMMIT_MESSAGE = "feat：简化连接窗口"
GIT_COMMIT_AUTHOR = "guoxuecheng"
GIT_COMMIT_DATE = "2025-11-24 20:34:32 +0800"

def get_version_string():
    """获取完整的版本信息字符串"""
    return f"v{VERSION} | 打包: {BUILD_DATE} | Commit: {GIT_COMMIT_HASH} ({GIT_BRANCH}) | {GIT_COMMIT_AUTHOR} | {GIT_COMMIT_MESSAGE}"

def get_detailed_info():
    """获取详细信息"""
    return {
        'version': VERSION,
        'build_date': BUILD_DATE,
        'git_branch': GIT_BRANCH,
        'git_commit_hash': GIT_COMMIT_HASH,
        'git_commit_message': GIT_COMMIT_MESSAGE,
        'git_commit_author': GIT_COMMIT_AUTHOR,
        'git_commit_date': GIT_COMMIT_DATE
    }
