# Form implementation generated from reading ui file '测试上位机.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(619, 588)
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setGeometry(QtCore.QRect(20, 20, 51, 24))
        self.pushButton.setObjectName("pushButton")
        self.checkBox = QtWidgets.QCheckBox(parent=Form)
        self.checkBox.setGeometry(QtCore.QRect(70, 50, 77, 20))
        self.checkBox.setObjectName("checkBox")
        self.pushButton_2 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 120, 75, 24))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 190, 75, 24))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 150, 75, 24))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 220, 75, 24))
        self.pushButton_5.setObjectName("pushButton_5")
        self.groupBox = QtWidgets.QGroupBox(parent=Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 310, 120, 80))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(30, 50, 54, 16))
        self.label.setObjectName("label")
        self.pushButton_6 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_6.setGeometry(QtCore.QRect(70, 20, 41, 24))
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 54, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(80, 80, 54, 16))
        self.label_3.setObjectName("label_3")
        self.mainWindowTextEdit = QtWidgets.QTextEdit(parent=Form)
        self.mainWindowTextEdit.setGeometry(QtCore.QRect(150, 10, 451, 571))
        self.mainWindowTextEdit.setObjectName("mainWindowTextEdit")
        self.pushButton_7 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_7.setGeometry(QtCore.QRect(20, 250, 75, 24))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_8.setGeometry(QtCore.QRect(20, 280, 75, 24))
        self.pushButton_8.setObjectName("pushButton_8")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "连接"))
        self.checkBox.setText(_translate("Form", "日志"))
        self.pushButton_2.setText(_translate("Form", "更新"))
        self.pushButton_3.setText(_translate("Form", "校准"))
        self.pushButton_4.setText(_translate("Form", "监控"))
        self.pushButton_5.setText(_translate("Form", "查询KB"))
        self.groupBox.setTitle(_translate("Form", "电量 电流 电压"))
        self.label.setText(_translate("Form", "注册"))
        self.pushButton_6.setText(_translate("Form", "断开"))
        self.label_2.setText(_translate("Form", "设备信息"))
        self.label_3.setText(_translate("Form", "TextLabel"))
        self.pushButton_7.setText(_translate("Form", "查询版本号"))
        self.pushButton_8.setText(_translate("Form", "PushButton"))
